template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "aleu1260"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ale"
__UND2C__ = "ale"
__UNDEFINED__ = "Aleut"
__UND__ = "ale"
